-- 계정 생성용 구문
-- CREATE USER got IDENTIFIED BY got;
-- GRANT CONNECT, RESOURCE TO got;

-----------------삭제------------------
--접속유저의 모든테이블 및 제약조건 삭제
/*
BEGIN
    FOR C IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE '||C.TABLE_NAME||' CASCADE CONSTRAINTS');
    END LOOP;
END;
/
--접속유저의 모든 시퀀스 삭제
BEGIN
FOR C IN (SELECT * FROM USER_SEQUENCES) LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||C.SEQUENCE_NAME;
END LOOP;
END;
/
--접속유저의 모든 뷰 삭제
BEGIN
FOR C IN (SELECT * FROM USER_VIEWS) LOOP
  EXECUTE IMMEDIATE 'DROP VIEW '||C.VIEW_NAME;
END LOOP;
END;
/
--접속유저의 모든 트리거 삭제
BEGIN
FOR C IN (SELECT * FROM USER_TRIGGERS) LOOP
  EXECUTE IMMEDIATE 'DROP TRIGGER '||C.TRIGGER_NAME;
END LOOP;
END;
/
*/
--------------------------------------------------
-------------------- AREA 관련 --------------------	
--------------------------------------------------
CREATE TABLE TB_AREA (
    AREA_NO NUMBER CONSTRAINT AREA_NO_PK PRIMARY KEY,
    AREA_NAME VARCHAR2(30) CONSTRAINT AREA_NAME_NN NOT NULL
);

COMMENT ON COLUMN TB_AREA.AREA_NO IS '지역 번호';
COMMENT ON COLUMN TB_AREA.AREA_NAME IS '지역 이름';

CREATE SEQUENCE SEQ_AREA_NO
NOCACHE;

INSERT INTO TB_AREA VALUES (SEQ_AREA_NO.NEXTVAL, '지역1');
INSERT INTO TB_AREA VALUES (SEQ_AREA_NO.NEXTVAL, '지역2');
INSERT INTO TB_AREA VALUES (SEQ_AREA_NO.NEXTVAL, '지역3');
--------------------------------------------------
----------------- MEMBER 관련 ---------------------	
--------------------------------------------------
CREATE TABLE TB_MEMBER (
    USER_NO NUMBER CONSTRAINT USER_NO_PK PRIMARY KEY,               
    USER_ID VARCHAR2(30) CONSTRAINT USER_ID_NN NOT NULL,
    USER_PWD VARCHAR2(100) CONSTRAINT USER_PWD_NN NOT NULL,  
    USER_NAME VARCHAR2(15) CONSTRAINT USER_NAME_NN NOT NULL, 
    USER_NICKNAME VARCHAR2(45) CONSTRAINT USER_NICKNAME_NN NOT NULL,
    USER_PHONE VARCHAR2(13) CONSTRAINT USER_PHONE_NN NOT NULL,              
    USER_EMAIL VARCHAR2(100) CONSTRAINT USER_EMAIL_NN NOT NULL,    
    USER_GENDER VARCHAR2(1) CONSTRAINT USER_GENDER_CK CHECK (USER_GENDER IN('M', 'F')),
    USER_ADDRESS VARCHAR2(100) CONSTRAINT USER_ADDRESS_NN NOT NULL,
    USER_AREA_NO NUMBER CONSTRAINT USER_AREA_NO_NN NOT NULL,
    USER_ENROLL_DATE DATE DEFAULT SYSDATE,
    USER_MODIFY_DATE DATE DEFAULT SYSDATE,
    USER_STATUS VARCHAR2(1) DEFAULT 'Y' CONSTRAINT USER_STATUS_CK CHECK (USER_STATUS IN('Y', 'A', 'B', 'N')),
    USER_ORIGIN_NAME VARCHAR2(100),
    USER_UPDATE_NAME VARCHAR2(100),
    CONSTRAINT USER_ID_UQ UNIQUE (USER_ID),
    CONSTRAINT USER_AREA_NO_FK FOREIGN KEY (USER_AREA_NO) REFERENCES TB_AREA(AREA_NO)
);

COMMENT ON COLUMN TB_MEMBER.USER_NO IS '회원 번호';
COMMENT ON COLUMN TB_MEMBER.USER_ID IS '회원 아이디';
COMMENT ON COLUMN TB_MEMBER.USER_PWD IS '회원 비밀번호';
COMMENT ON COLUMN TB_MEMBER.USER_NAME IS '회원 이름';
COMMENT ON COLUMN TB_MEMBER.USER_NICKNAME IS '회원 닉네임';
COMMENT ON COLUMN TB_MEMBER.USER_PHONE IS '회원 전화번호';
COMMENT ON COLUMN TB_MEMBER.USER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN TB_MEMBER.USER_GENDER IS '회원 성별';
COMMENT ON COLUMN TB_MEMBER.USER_ADDRESS IS '회원 주소';
COMMENT ON COLUMN TB_MEMBER.USER_AREA_NO IS '회원 관심지';
COMMENT ON COLUMN TB_MEMBER.USER_ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN TB_MEMBER.USER_MODIFY_DATE IS '회원 수정일';
COMMENT ON COLUMN TB_MEMBER.USER_STATUS IS '회원 상태값 (Y : 사용중 / N : 탈퇴 / A : 관리자 / B : 블랙리스트)';
COMMENT ON COLUMN TB_MEMBER.USER_ORIGIN_NAME IS '회원 프로필 원본';
COMMENT ON COLUMN TB_MEMBER.USER_UPDATE_NAME IS '회원 프로필 변경';

INSERT INTO TB_MEMBER VALUES (0, 'admin', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '리상룡', '관리자', '010-1234-5678', 'admin@kh.or.kr', 'M', '서울시 강남구 역삼동', 1, '2024-03-26', '2024-03-26', 'A', 'got_admin.png', 'resources/images/member/got_admin.png');

CREATE SEQUENCE SEQ_USER_NO
NOCACHE;

INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user01', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '김재영', '돼지불백집이쑤시개도둑', '010-0526-1564', 'nano@kh.or.kr', 'M', '서울시 강동구 천호동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_nano.png', 'resources/uploadFiles/member/2024032609000082221.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user02', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '류은송', '공중화장실휴지도둑', '010-1593-8423', 'resong@kh.or.kr', 'F', '서울시 광진구 중곡동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_eunsong.png', 'resources/uploadFiles/member/2024032609000082222.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user03', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '박민규', '기사식당명함도둑', '010-7513-1513', 'park@kh.or.kr', 'M', '서울시 강동구 천호동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_kyuu.jpg', 'resources/uploadFiles/member/2024032609000082223.jpg');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user04', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '신나리', '휴게소컵도둑', '010-5238-1728', 'shin@kh.or.kr', 'F', '서울시 강동구 천호동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_berry.jpg', 'resources/uploadFiles/member/2024032609000082224.jpg');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user05', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '이상용', '주호민이알려주는고데기사용법', '010-4215-9178', 'leessang@kh.or.kr', 'M', '서울시 강동구 천호동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_lee.jpeg', 'resources/uploadFiles/member/2024032609000082225.jpg');

INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user06', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '임하리', '주인', '010-1721-8432', 'eiwq145@kh.or.kr', 'F', '서울시 영등포구 당산동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082226.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user07', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '유재섬', '사쿠라', '010-1547-1513', 'mpkm046@kh.or.kr', 'M', '서울시 영등포구 대림동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082227.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user08', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '나경운', '저는김치입니다', '010-9764-5286', 'mipmw04@kh.or.kr', 'M', '서울시 영등포구 도림동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082228.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user09', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '권상오', '저는돼지입니다', '010-3162-6134', 'msdh53@kh.or.kr', 'M', '서울시 영등포구 신길동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082229.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user10', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '손태양', '저는해병입니다', '010-4451-8765', 'mkls18@kh.or.kr', 'M', '서울시 영등포구 양화동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082230.png');

INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user11', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '강혜양', '개털알레르기', '010-4845-1411', 'qwe048@kh.or.kr', 'M', '서울시 종로구 계동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082231.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user12', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '이산균', '빗자루', '010-1172-4487', 'hrww504@kh.or.kr', 'M', '서울시 종로구 가회동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082232.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user13', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '난혜진', '무지개', '010-0531-9204', 'zmuvs68@kh.or.kr', 'M', '서울시 종로구 공평동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082233.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user14', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '나준상', '솜사탕', '010-9174-1840', 'miop0qw@kh.or.kr', 'M', '서울시 종로구 경운동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082234.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user15', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '홍은하', '기부가좋아', '010-7841-1230', 'nmhr50@kh.or.kr', 'M', '서울시 종로구 교남동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082235.png');

INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user16', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '윤중신', '총학생회회장', '010-8415-1510', 'qq9ewq9@kh.or.kr', 'M', '서울시 용산구 동빙고동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082236.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user17', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '전나라', '레스토랑포크도둑', '010-9798-2310', 'mksk045@kh.or.kr', 'M', '서울시 용산구 갈월동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082237.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user18', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '여성진', '아쿠아리움이끼도둑', '010-7812-1045', 'q0546@kh.or.kr', 'M', '서울시 용산구 문배동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082238.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user19', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '강지영', '스타벅스전기도둑', '010-9963-1520', 'ngd05@kh.or.kr', 'M', '서울시 용산구 이촌동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082239.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user20', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '이소근', '와이파이비번주세요', '010-2475-1723', 'zxc504@kh.or.kr', 'M', '서울시 용산구 청암동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082240.png');

INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user21', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '감병지', '커튼사주세요', '010-7748-5176', 'e045q@kh.or.kr', 'M', '서울시 중랑구 망우동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082241.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user22', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '김민경', '메N괌', '010-1547-7021', 'wqe142a@kh.or.kr', 'M', '서울시 중랑구 면목동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082242.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user23', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '김호동', '민족전통놀이맞고', '010-0985-2361', 'qwrq1a@kh.or.kr', 'M', '서울시 중랑구 중화동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082243.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user24', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '김수연', '아뇨뚱인데요', '010-2049-8365', 'nqwe05@kh.or.kr', 'M', '서울시 중랑구 상봉동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082244.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user25', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '하지운', '언제까지일까', '010-0784-5956', 'qmip@kh.or.kr', 'M', '서울시 중랑구 묵동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082245.png');

INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user26', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '온조완', '집가고싶다', '010-0524-1504', 'zxna@kh.or.kr', 'M', '서울시 성북구 상월곡동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082246.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user27', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '양현심', '알빠누', '010-8142-2042', 'qnwi@kh.or.kr', 'M', '서울시 성북구 석관동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082247.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user28', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '박철영', '초코브라우니', '010-7402-0351', 'wmqui@kh.or.kr', 'M', '서울시 성북구 성북동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082248.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user29', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '김아연', '맘모스커피사랑해', '010-0152-0429', 'nonus@kh.or.kr', 'M', '서울시 성북구 돈암동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082249.png');
INSERT INTO TB_MEMBER VALUES (SEQ_USER_NO.NEXTVAL, 'user30', '$2a$10$aY0LWsAmndgyE8oRH4Tneu5eAQC7UdlVXj2rk.Ob9cchdtqY/hbg.', '오윤서', '도장', '010-0875-0142', 'tpq2@kh.or.kr', 'M', '서울시 성북구 길음동', 1, '2024-03-26', '2024-03-26', 'Y', 'got_mem.png', 'resources/uploadFiles/member/2024032609000082250.png');
--------------------------------------------------
-------------- ANNOUNCEMENT 관련 ------------------	
--------------------------------------------------
CREATE TABLE TB_ANNOUNCEMENT (
    ANNOUNCEMENT_NO NUMBER CONSTRAINT ANNOUNCEMENT_NO_PK PRIMARY KEY,
    ANNOUNCEMENT_TITLE VARCHAR2(100) CONSTRAINT ANNOUNCEMENT_TITLE_NN NOT NULL,
    ANNOUNCEMENT_CONTENT VARCHAR2(4000) CONSTRAINT ANNOUNCEMENT_CONTENT_NN NOT NULL,
    ANNOUNCEMENT_WRITER NUMBER CONSTRAINT ANNOUNCEMENT_WRITER_NN NOT NULL,
    ANNOUNCEMENT_COUNT NUMBER DEFAULT 0,
    ANNOUNCEMENT_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT ANNOUNCEMENT_CREATE_DATE_NN NOT NULL,
    ANNOUNCEMENT_STATUS VARCHAR2(1) DEFAULT 'Y' CONSTRAINT ANNOUNCEMENT_STATUS_CK CHECK (ANNOUNCEMENT_STATUS IN('Y', 'N')),
    CONSTRAINT ANNOUNCEMENT_WRITER_FK FOREIGN KEY(ANNOUNCEMENT_WRITER) REFERENCES TB_MEMBER(USER_NO)
);

COMMENT ON COLUMN TB_ANNOUNCEMENT.ANNOUNCEMENT_NO IS '공지 번호';
COMMENT ON COLUMN TB_ANNOUNCEMENT.ANNOUNCEMENT_TITLE IS '공지 제목';
COMMENT ON COLUMN TB_ANNOUNCEMENT.ANNOUNCEMENT_CONTENT IS '공지 내용';
COMMENT ON COLUMN TB_ANNOUNCEMENT.ANNOUNCEMENT_WRITER IS '공지 작성자회원번호';
COMMENT ON COLUMN TB_ANNOUNCEMENT.ANNOUNCEMENT_COUNT IS '공지 조회수';
COMMENT ON COLUMN TB_ANNOUNCEMENT.ANNOUNCEMENT_CREATE_DATE IS '공지 작성일';
COMMENT ON COLUMN TB_ANNOUNCEMENT.ANNOUNCEMENT_STATUS IS '공지 상태값 (Y : 게시 / N : 비게시)';

CREATE SEQUENCE SEQ_ANNOUNCEMENT_NO
NOCACHE;

INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '오픈! 갓물주!', '갓물주는 부동산 정보 조회 사이트로 여러분을 찾아뵙습니다.', 0, DEFAULT, '2024-03-26', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '갓물주 서비스 이용약관 개정 및 신설 안내', '약관이 개정되었기에, 참고 부탁드립니다.', 0, DEFAULT, '2024-03-27', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '서비스 정상화 안내', '앞으로 더욱 안정적인 서비스를 제공할 수 있도록 노력하겠습니다.', 0, DEFAULT, '2024-03-28', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '공지제목4!', '공지내용4', 0, DEFAULT, '2024-03-29', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '갓물주 개인정보처리방침 주요 개정사항 안내', '변경된 방침을 참고하여 서비스 이용 부탁드립니다.', 0, DEFAULT, '2024-03-30', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '공지제목6!', '공지내용6', 0, DEFAULT, '2024-03-31', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '공지제목7!', '공지내용7', 0, DEFAULT, '2024-04-01', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '갓물주 서비스 이용약관 개정 및 신설 안내', '약관이 개정되었기에, 참고 부탁드립니다.', 0, DEFAULT, '2024-04-02', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '공지제목9!', '공지내용9', 0, DEFAULT, '2024-04-03', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '공지제목10!', '공지내용10', 0, DEFAULT, '2024-04-04', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '갓물주 개인정보처리방침 주요 개정사항 안내', '변경된 방침을 참고하여 서비스 이용 부탁드립니다.', 0, DEFAULT, '2024-04-05', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '서비스 정상화 안내', '앞으로 더욱 안정적인 서비스를 제공할 수 있도록 노력하겠습니다.', 0, DEFAULT, '2024-04-06', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '공지제목13!', '공지내용13', 0, DEFAULT, '2024-04-07', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '공지제목14!', '공지내용14', 0, DEFAULT, '2024-04-08', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '갓물주 서비스 이용약관 개정 및 신설 안내', '약관이 개정되었기에, 참고 부탁드립니다.', 0, DEFAULT, '2024-04-09', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '공지제목16!', '공지내용16', 0, DEFAULT, '2024-04-10', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '공지제목17!', '공지내용17', 0, DEFAULT, '2024-04-11', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '갓물주 허위매물 예방 안내', '방 내부 구조를 알아보기 힘든 사진은 허위매물일 가능성이 높습니다.', 0, DEFAULT, '2024-04-12', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '공지제목19!', '공지내용19', 0, DEFAULT, '2024-04-13', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '갓물주 서비스 이용약관 개정 및 신설 안내', '약관이 개정되었기에, 참고 부탁드립니다.', 0, DEFAULT, '2024-04-14', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '서비스 정상화 안내', '앞으로 더욱 안정적인 서비스를 제공할 수 있도록 노력하겠습니다.', 0, DEFAULT, '2024-04-15', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '갓물주 개인정보처리방침 주요 개정사항 안내', '변경된 방침을 참고하여 서비스 이용 부탁드립니다.', 0, DEFAULT, '2024-04-16', DEFAULT);
INSERT INTO TB_ANNOUNCEMENT VALUES (SEQ_ANNOUNCEMENT_NO.NEXTVAL, '공지제목23!', '공지내용23', 0, DEFAULT, '2024-04-17', DEFAULT);
--------------------------------------------------
----------------- FAQ 게시판 관련 ------------------	
--------------------------------------------------
CREATE TABLE TB_FAQ (
    FAQ_NO NUMBER CONSTRAINT FAQ_NO_PK PRIMARY KEY,
    FAQ_TITLE VARCHAR2(100) CONSTRAINT FAQ_TITLE_NN NOT NULL,
    FAQ_CONTENT VARCHAR2(4000) CONSTRAINT FAQ_CONTENT_NN NOT NULL,
    FAQ_WRITER NUMBER CONSTRAINT FAQ_WRITER_NN NOT NULL,
    FAQ_COUNT NUMBER DEFAULT 0,
    FAQ_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT FAQ_CREATE_DATE_NN NOT NULL,
    FAQ_MODIFY_DATE DATE DEFAULT SYSDATE,
    FAQ_STATUS VARCHAR2(1) DEFAULT 'Y' CONSTRAINT FAQ_STATUS_CK CHECK (FAQ_STATUS IN('Y', 'N')),
    CONSTRAINT FAQ_WRITER_FK FOREIGN KEY(FAQ_WRITER) REFERENCES TB_MEMBER(USER_NO)
);

COMMENT ON COLUMN TB_FAQ.FAQ_NO IS '자주묻는질문 번호';
COMMENT ON COLUMN TB_FAQ.FAQ_TITLE IS '자주묻는질문 질문';
COMMENT ON COLUMN TB_FAQ.FAQ_CONTENT IS '자주묻는질문 답변';
COMMENT ON COLUMN TB_FAQ.FAQ_WRITER IS '자주묻는질문 작성자회원번호';
COMMENT ON COLUMN TB_FAQ.FAQ_COUNT IS '자주묻는질문 조회수';
COMMENT ON COLUMN TB_FAQ.FAQ_CREATE_DATE IS '자주묻는질문 작성일';
COMMENT ON COLUMN TB_FAQ.FAQ_MODIFY_DATE IS '자주묻는질문 수정일';
COMMENT ON COLUMN TB_FAQ.FAQ_STATUS IS '자주묻는질문 상태값 (Y : 게시 / N : 비게시)';

CREATE SEQUENCE SEQ_FAQ_NO
NOCACHE;

INSERT INTO TB_FAQ VALUES (SEQ_FAQ_NO.NEXTVAL, '회원 정보 변경은 어떻게 하나요?', '마이페이지 내 회원정보수정에서 언제든 변경할 수 있어요.', 0, DEFAULT, '2024-03-26', '2024-03-26', DEFAULT);
INSERT INTO TB_FAQ VALUES (SEQ_FAQ_NO.NEXTVAL, '갓물주는 어떤 서비스인가요?', '국내 최고 오픈형 부동산 플랫폼입니다!', 0, DEFAULT, '2024-03-26', '2024-03-26', DEFAULT);
INSERT INTO TB_FAQ VALUES (SEQ_FAQ_NO.NEXTVAL, '회원가입을 하면 어떤 점이 좋나요?', '찜하기와 게시 및 기타 서비스를 제공합니다.', 0, DEFAULT, '2024-03-26', '2024-03-26', DEFAULT);
INSERT INTO TB_FAQ VALUES (SEQ_FAQ_NO.NEXTVAL, '갓물주에 등록된 방은 믿을 수 있나요?', '갓물주는 믿을 수 있는 정보만을 제공합니다.', 0, DEFAULT, '2024-03-26', '2024-03-26', DEFAULT);
INSERT INTO TB_FAQ VALUES (SEQ_FAQ_NO.NEXTVAL, '취득세도 계산하고 싶어요', '기타의 세금계산기를 이용해주세요!', 0, DEFAULT, '2024-03-26', '2024-03-26', DEFAULT);
INSERT INTO TB_FAQ VALUES (SEQ_FAQ_NO.NEXTVAL, '이용 시간은 어떻게 되나요?', '24시간 이용 가능합니다!', 0, DEFAULT, '2024-03-26', '2024-03-26', DEFAULT);
INSERT INTO TB_FAQ VALUES (SEQ_FAQ_NO.NEXTVAL, '유료서비스도 있나요?', '갓물주는 모두 무료로 제공됩니다!', 0, DEFAULT, '2024-03-26', '2024-03-26', DEFAULT);
INSERT INTO TB_FAQ VALUES (SEQ_FAQ_NO.NEXTVAL, '질문은 어디에 남길 수 있나요?', '고객센터 메뉴를 이용해주세요!', 0, DEFAULT, '2024-03-26', '2024-03-26', DEFAULT);
INSERT INTO TB_FAQ VALUES (SEQ_FAQ_NO.NEXTVAL, '마음에 드는 부동산 저장하고 싶어요', '찜하기를 이용해주시면 됩니다!', 0, DEFAULT, '2024-03-26', '2024-03-26', DEFAULT);
INSERT INTO TB_FAQ VALUES (SEQ_FAQ_NO.NEXTVAL, '우리 동네 사진을 자랑하고 싶어요', '커뮤니티에 등록해주세요!', 0, DEFAULT, '2024-03-26', '2024-03-26', DEFAULT);
--------------------------------------------------
----------------- QNA 게시판 관련 ------------------	
--------------------------------------------------
CREATE TABLE TB_QNA (
    QNA_NO NUMBER CONSTRAINT QNA_NO_PK PRIMARY KEY,
    QNA_WRITER NUMBER CONSTRAINT QNA_WRITER_NN NOT NULL,
    QNA_TITLE VARCHAR2(100) CONSTRAINT QNA_TITLE_NN NOT NULL,
    QNA_CONTENT VARCHAR2(4000) CONSTRAINT QNA_CONTENT_NN NOT NULL,
    QNA_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT QNA_CREATE_DATE_NN NOT NULL,
    QNA_MODIFY_DATE DATE DEFAULT SYSDATE,
    QNA_ANSWER_STATUS VARCHAR2(1) DEFAULT 'N' CONSTRAINT QNA_ANSWER_STATUS_CK CHECK(QNA_ANSWER_STATUS IN('Y', 'N')),
    QNA_TYPE NUMBER CONSTRAINT QNA_TYPE_CK CHECK(QNA_TYPE IN(1, 2)),
    QNA_STATUS VARCHAR2(1) DEFAULT 'Y' CONSTRAINT QNA_STATUS_CK CHECK(QNA_STATUS IN('Y', 'N')),
    CONSTRAINT QNA_WRITER_FK FOREIGN KEY (QNA_WRITER) REFERENCES TB_MEMBER(USER_NO)
);

COMMENT ON COLUMN TB_QNA.QNA_NO IS 'QNA 번호';
COMMENT ON COLUMN TB_QNA.QNA_WRITER IS 'QNA 작성자회원번호';
COMMENT ON COLUMN TB_QNA.QNA_TITLE IS 'QNA 제목';
COMMENT ON COLUMN TB_QNA.QNA_CONTENT IS 'QNA 내용';
COMMENT ON COLUMN TB_QNA.QNA_CREATE_DATE IS 'QNA 작성일';
COMMENT ON COLUMN TB_QNA.QNA_MODIFY_DATE IS 'QNA 수정일';
COMMENT ON COLUMN TB_QNA.QNA_ANSWER_STATUS IS 'QNA 답변 상태값 (Y : 답변완료 / N : 답변대기)';
COMMENT ON COLUMN TB_QNA.QNA_TYPE IS 'QNA 유형 (1 : 일반 / 2 : 비밀)';
COMMENT ON COLUMN TB_QNA.QNA_STATUS IS 'QNA 상태값 (Y : 게시 / N : 비게시)';

CREATE SEQUENCE SEQ_QNA_NO
NOCACHE;

INSERT INTO TB_QNA(QNA_NO, QNA_WRITER, QNA_TITLE, QNA_CONTENT, QNA_CREATE_DATE, QNA_ANSWER_STATUS, QNA_TYPE, QNA_STATUS) 
VALUES(SEQ_QNA_NO.NEXTVAL, 2, '이용 문의 드립니다.', '회원 신고기능도 추가예정인가요?', '2024-03-26', 'N', 1, 'Y');

INSERT INTO TB_QNA(QNA_NO, QNA_WRITER, QNA_TITLE, QNA_CONTENT, QNA_CREATE_DATE, QNA_ANSWER_STATUS, QNA_TYPE, QNA_STATUS) 
VALUES(SEQ_QNA_NO.NEXTVAL, 3, '격리 요청', '주호민이라는 회원 차단좀 해주세요', '2024-03-27', 'N', 2, 'Y');

INSERT INTO TB_QNA(QNA_NO, QNA_WRITER, QNA_TITLE, QNA_CONTENT, QNA_CREATE_DATE, QNA_ANSWER_STATUS, QNA_TYPE, QNA_STATUS) 
VALUES(SEQ_QNA_NO.NEXTVAL, 4, '이용 문의', '사이트에 광고 게시 문의드리고자합니다. 담당자 알려주세요.', '2024-03-28', 'N', 1, 'Y');

INSERT INTO TB_QNA(QNA_NO, QNA_WRITER, QNA_TITLE, QNA_CONTENT, QNA_CREATE_DATE, QNA_ANSWER_STATUS, QNA_TYPE, QNA_STATUS) 
VALUES(SEQ_QNA_NO.NEXTVAL, 5, '기능 문의', '추가 예정인 기능이 어떤 것이 있을까요?', '2024-03-29', 'N', 1, 'Y');

INSERT INTO TB_QNA(QNA_NO, QNA_WRITER, QNA_TITLE, QNA_CONTENT, QNA_CREATE_DATE, QNA_ANSWER_STATUS, QNA_TYPE, QNA_STATUS) 
VALUES(SEQ_QNA_NO.NEXTVAL, 2, '제안드립니다.', '파트너십 관련 문의는 어디에 남기면 좋을까요?', '2024-03-30', 'N', 2, 'Y');
--------------------------------------------------
----------------- QNA 답변 관련 ------------------	
--------------------------------------------------
CREATE TABLE TB_QNA_ANSWER (
    QNA_ANSWER_NO NUMBER CONSTRAINT QNA_ANSWER_NO_PK PRIMARY KEY,
    QNA_ANSWER_REF_NO NUMBER CONSTRAINT QNA_ANSWER_REF_NO_NN NOT NULL,
    QNA_ANSWER_CONTENT VARCHAR2(1000) CONSTRAINT QNA_ANSWER_CONTENT NOT NULL,
    QNA_ANSWER_WRITER NUMBER CONSTRAINT QNA_ANSWER_WRITER_NN NOT NULL,
    QNA_ANSWER_CREATE_DATE DATE,
    QNA_ANSWER_MODIFY_DATE DATE,
    QNA_ANSWER_TYPE NUMBER CONSTRAINT QNA_ANSWER_TYPE_NN NOT NULL,
    QNA_ANSWER_STATUS VARCHAR2(1),
    CONSTRAINT QNA_ANSWER_REF_NO_FK FOREIGN KEY (QNA_ANSWER_REF_NO) REFERENCES TB_QNA(QNA_NO)
);

COMMENT ON COLUMN TB_QNA_ANSWER.QNA_ANSWER_NO IS '답변 번호';
COMMENT ON COLUMN TB_QNA_ANSWER.QNA_ANSWER_REF_NO IS '참조 QNA 번호';
COMMENT ON COLUMN TB_QNA_ANSWER.QNA_ANSWER_CONTENT IS '답변 내용';
COMMENT ON COLUMN TB_QNA_ANSWER.QNA_ANSWER_WRITER IS '답변 작성자 회원번호';
COMMENT ON COLUMN TB_QNA_ANSWER.QNA_ANSWER_CREATE_DATE IS '답변 작성일';
COMMENT ON COLUMN TB_QNA_ANSWER.QNA_ANSWER_MODIFY_DATE IS '답변 수정일';
COMMENT ON COLUMN TB_QNA_ANSWER.QNA_ANSWER_TYPE IS '답변 유형 (1 : 일반 / 2 : 비밀)';
COMMENT ON COLUMN TB_QNA_ANSWER.QNA_ANSWER_STATUS IS '답변 상태값 (Y : 게시 / N : 비게시)';

CREATE SEQUENCE SEQ_QNA_ANSWER_NO
NOCACHE;
--------------------------------------------------
-------------------- APT 관련 ----------------------	
--------------------------------------------------
ALTER TABLE TB_APT
ADD CONSTRAINT APT_NO_PK PRIMARY KEY (APT_NO);

COMMENT ON COLUMN TB_APT.APT_NO IS '아파트 번호';
COMMENT ON COLUMN TB_APT.APT_SELLING_TYPE IS '아파트 거래방식';
COMMENT ON COLUMN TB_APT.APT_LOCATION IS '아파트 좌표';
COMMENT ON COLUMN TB_APT.APT_NAME IS '아파트 이름';
COMMENT ON COLUMN TB_APT.APT_INTRODUCE IS '아파트 소개말';
COMMENT ON COLUMN TB_APT.APT_PRICE IS '아파트 가격';
COMMENT ON COLUMN TB_APT.APT_IMG_URL IS '아파트 대표이미지';
COMMENT ON COLUMN TB_APT.APT_IMG_URLS IS '아파트 세부이미지';
COMMENT ON COLUMN TB_APT.APT_DESC IS '아파트 층고 / 평수 / 관리비';
COMMENT ON COLUMN TB_APT.APT_REVIEW IS '아파트 리뷰';
COMMENT ON COLUMN TB_APT.APT_COUNT IS '아파트 조회수';
COMMENT ON COLUMN TB_APT.APT_CREATE_DATE IS '아파트 수정일';
COMMENT ON COLUMN TB_APT.APT_STATUS IS '아파트 상태';
COMMENT ON COLUMN TB_APT.APT_MEMO IS '아파트 상세설명';
COMMENT ON COLUMN TB_APT.APT_ROOM_SIZE IS '아파트 전용면적';
COMMENT ON COLUMN TB_APT.APT_PROVISION_SIZE IS '아파트 공급면적';
COMMENT ON COLUMN TB_APT.APT_ADDRESS IS '아파트 주소';
COMMENT ON COLUMN TB_APT.APT_DONG IS '아파트 동';
COMMENT ON COLUMN TB_APT.APT_HO IS '아파트 호';
COMMENT ON COLUMN TB_APT.APT_TAGS IS '아파트 단기/주차/풀옵션/보안 등';
COMMENT ON COLUMN TB_APT.APT_BEDS IS '아파트 방 수';
COMMENT ON COLUMN TB_APT.APT_BATH IS '아파트 화장실 수';
COMMENT ON COLUMN TB_APT.APT_ENTRANCE_TYPE IS '아파트 계단식/복도식';
COMMENT ON COLUMN TB_APT.APT_SEARCH IS '아파트 검색 수';
--------------------------------------------------
-------------------- TOWN 관련 --------------------	
--------------------------------------------------
CREATE TABLE TB_TOWN (
    TOWN_NO NUMBER CONSTRAINT TOWN_NO_PK PRIMARY KEY,
    TOWN_WRITER VARCHAR2(50) CONSTRAINT TOWN_WRITER_NN NOT NULL,
    TOWN_WRITER_IMG VARCHAR2(100) CONSTRAINT TOWN_WRITER_IMG_NN NOT NULL,
    TOWN_TITLE VARCHAR2(100) CONSTRAINT TOWN_TITLE_NN NOT NULL,
    TOWN_CONTENT VARCHAR2(4000) CONSTRAINT TOWN_CONTENT_NN NOT NULL,
    TOWN_STAR NUMBER DEFAULT 0,
    TOWN_LIKES NUMBER DEFAULT 0,
    TOWN_CLICK NUMBER DEFAULT 0,
    TOWN_REPLY_COUNT NUMBER DEFAULT 0,
    TOWN_CREATE_DATE DATE DEFAULT SYSDATE,
    TOWN_MODIFY_DATE DATE DEFAULT SYSDATE,
    TOWN_STATUS VARCHAR2(1) DEFAULT 'Y' CONSTRAINT TOWN_STATUS_CK CHECK(TOWN_STATUS IN('Y', 'N')),
    TOWN_THUMBNAIL VARCHAR2(1000),
    TOWN_DETAIL_IMG1 VARCHAR2(1000),
    TOWN_DETAIL_IMG2 VARCHAR2(1000),
    TOWN_DETAIL_IMG3 VARCHAR2(1000),
    TOWN_DETAIL_IMG4 VARCHAR2(1000),
    TOWN_DETAIL_IMG5 VARCHAR2(1000)
);

COMMENT ON COLUMN TB_TOWN.TOWN_NO IS '동네소식 번호';
COMMENT ON COLUMN TB_TOWN.TOWN_WRITER IS '동네소식 작성자';
COMMENT ON COLUMN TB_TOWN.TOWN_WRITER_IMG IS '동네소식 작성자 프로필';
COMMENT ON COLUMN TB_TOWN.TOWN_TITLE IS '동네소식 제목';
COMMENT ON COLUMN TB_TOWN.TOWN_CONTENT IS '동네소식 내용';
COMMENT ON COLUMN TB_TOWN.TOWN_STAR IS '동네소식 즐겨찾기';
COMMENT ON COLUMN TB_TOWN.TOWN_LIKES IS '동네소식 좋아요';
COMMENT ON COLUMN TB_TOWN.TOWN_CLICK IS '동네소식 조회수';
COMMENT ON COLUMN TB_TOWN.TOWN_REPLY_COUNT IS '동네소식 댓글수';
COMMENT ON COLUMN TB_TOWN.TOWN_CREATE_DATE IS '동네소식 작성일';
COMMENT ON COLUMN TB_TOWN.TOWN_MODIFY_DATE IS '동네소식 수정일';
COMMENT ON COLUMN TB_TOWN.TOWN_STATUS IS '동네소식 상태(Y : 게시 / N : 비게시)';
COMMENT ON COLUMN TB_TOWN.TOWN_THUMBNAIL IS '동네소식 대표이미지';
COMMENT ON COLUMN TB_TOWN.TOWN_DETAIL_IMG1 IS '동네소식 상세이미지';
COMMENT ON COLUMN TB_TOWN.TOWN_DETAIL_IMG2 IS '동네소식 상세이미지';
COMMENT ON COLUMN TB_TOWN.TOWN_DETAIL_IMG3 IS '동네소식 상세이미지';
COMMENT ON COLUMN TB_TOWN.TOWN_DETAIL_IMG4 IS '동네소식 상세이미지';
COMMENT ON COLUMN TB_TOWN.TOWN_DETAIL_IMG5 IS '동네소식 상세이미지';

CREATE SEQUENCE SEQ_TOWN_NO
NOCACHE;

INSERT INTO TB_TOWN (TOWN_NO, TOWN_WRITER, TOWN_WRITER_IMG, TOWN_TITLE, TOWN_CONTENT, TOWN_STAR, TOWN_LIKES , TOWN_CLICK, TOWN_REPLY_COUNT, TOWN_THUMBNAIL) VALUES (SEQ_TOWN_NO.NEXTVAL, '돼지불백집이쑤시개도둑', 'resources/uploadFiles/member/2024032609000082221.png', '이런 곳은 어때요?', '갖고싶다..', 1, 10, 15, 3, 'resources/uploadFiles/town/2024032609000050001.jpg');
INSERT INTO TB_TOWN (TOWN_NO, TOWN_WRITER, TOWN_WRITER_IMG, TOWN_TITLE, TOWN_CONTENT, TOWN_STAR, TOWN_LIKES , TOWN_CLICK, TOWN_REPLY_COUNT, TOWN_THUMBNAIL) VALUES (SEQ_TOWN_NO.NEXTVAL, '공중화장실휴지도둑', 'resources/uploadFiles/member/2024032609000082222.png', '무료하네요', '너무 심심한 하루에요', 1, 7, 3, 0, 'resources/uploadFiles/town/2024032609000050002.jpg');
INSERT INTO TB_TOWN (TOWN_NO, TOWN_WRITER, TOWN_WRITER_IMG, TOWN_TITLE, TOWN_CONTENT, TOWN_STAR, TOWN_LIKES , TOWN_CLICK, TOWN_REPLY_COUNT, TOWN_THUMBNAIL) VALUES (SEQ_TOWN_NO.NEXTVAL, '기사식당명함도둑', 'resources/uploadFiles/member/2024032609000082223.jpg', '주말에 다녀온 곳', '너무 이쁘길래 찍어왔는데 어때요?', 0, 8, 5, 2, 'resources/uploadFiles/town/2024032609000050003.jpg');
INSERT INTO TB_TOWN (TOWN_NO, TOWN_WRITER, TOWN_WRITER_IMG, TOWN_TITLE, TOWN_CONTENT, TOWN_STAR, TOWN_LIKES , TOWN_CLICK, TOWN_REPLY_COUNT, TOWN_THUMBNAIL) VALUES (SEQ_TOWN_NO.NEXTVAL, '휴게소컵도둑', 'resources/uploadFiles/member/2024032609000082224.jpg', '벚꽃이 이쁘길래 찍어봤어요^^', '다들 좋은 하루 보내세요^^', 2, 13, 20, 1, 'resources/uploadFiles/town/2024032609000050004.jpg');
INSERT INTO TB_TOWN (TOWN_NO, TOWN_WRITER, TOWN_WRITER_IMG, TOWN_TITLE, TOWN_CONTENT, TOWN_STAR, TOWN_LIKES , TOWN_CLICK, TOWN_REPLY_COUNT, TOWN_THUMBNAIL) VALUES (SEQ_TOWN_NO.NEXTVAL, '주호민이알려주는고데기사용법', 'resources/uploadFiles/member/2024032609000082225.jpg', '최고의 가정집!', '이런 곳에서 살고 싶네요ㅠㅠ', 2, 15, 17, 0, 'resources/uploadFiles/town/2024032609000050005.jpg');
INSERT INTO TB_TOWN (TOWN_NO, TOWN_WRITER, TOWN_WRITER_IMG, TOWN_TITLE, TOWN_CONTENT, TOWN_STAR, TOWN_LIKES , TOWN_CLICK, TOWN_REPLY_COUNT, TOWN_THUMBNAIL) VALUES (SEQ_TOWN_NO.NEXTVAL, '돼지불백집이쑤시개도둑', 'resources/uploadFiles/member/2024032609000082221.png', '주말 나들이', '요즘 날씨가 너무 좋아요 ㅎㅎ', 0, 21, 26, 0, 'resources/uploadFiles/town/2024032609000050006.jpg');
--------------------------------------------------
----------------- TOWN-REPLY 관련 -----------------	
--------------------------------------------------
CREATE TABLE TB_TOWN_REPLY (
    TOWN_REPLY_NO NUMBER CONSTRAINT TOWN_REPLY_NO_PK PRIMARY KEY,
    TOWN_REPLY_REF_NO NUMBER CONSTRAINT TOWN_REPLY_REF_NO_NN NOT NULL,
    TOWN_REPLY_WRITER VARCHAR2(50) CONSTRAINT TOWN_REPLY_WRITER_NN NOT NULL,
    TOWN_REPLY_WRITER_IMG VARCHAR2(100) CONSTRAINT TOWN_REPLY_WRITER_IMG_NN NOT NULL,
    TOWN_REPLY_CONTENT VARCHAR2(4000) CONSTRAINT TOWN_REPLY_CONTENT_NN NOT NULL,
    TOWN_REPLY_CREATE_DATE DATE DEFAULT SYSDATE,
    TOWN_REPLY_MODIFY_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT TOWN_REPLY_REF_NO_FK FOREIGN KEY (TOWN_REPLY_REF_NO) REFERENCES TB_TOWN(TOWN_NO)
);

COMMENT ON COLUMN TB_TOWN_REPLY.TOWN_REPLY_NO IS '동네소식 댓글 번호';
COMMENT ON COLUMN TB_TOWN_REPLY.TOWN_REPLY_REF_NO IS '동네소식 번호';
COMMENT ON COLUMN TB_TOWN_REPLY.TOWN_REPLY_WRITER IS '동네소식 댓글 작성자';
COMMENT ON COLUMN TB_TOWN_REPLY.TOWN_REPLY_WRITER_IMG IS '동네소식 댓글 작성자 프로필';
COMMENT ON COLUMN TB_TOWN_REPLY.TOWN_REPLY_CONTENT IS '동네소식 댓글 내용';
COMMENT ON COLUMN TB_TOWN_REPLY.TOWN_REPLY_CREATE_DATE IS '동네소식 댓글 작성일';
COMMENT ON COLUMN TB_TOWN_REPLY.TOWN_REPLY_MODIFY_DATE IS '동네소식 댓글 수정일';

CREATE SEQUENCE SEQ_TOWN_REPLY_NO
NOCACHE;

INSERT INTO TB_TOWN_REPLY (TOWN_REPLY_NO, TOWN_REPLY_REF_NO, TOWN_REPLY_WRITER, TOWN_REPLY_WRITER_IMG, TOWN_REPLY_CONTENT)
VALUES (SEQ_TOWN_REPLY_NO.NEXTVAL, 1, '공중화장실휴지도둑', 'resources/uploadFiles/member/2024032609000082222.png', '갖고 싶다..');
INSERT INTO TB_TOWN_REPLY (TOWN_REPLY_NO, TOWN_REPLY_REF_NO, TOWN_REPLY_WRITER, TOWN_REPLY_WRITER_IMG, TOWN_REPLY_CONTENT)
VALUES (SEQ_TOWN_REPLY_NO.NEXTVAL, 1, '공중화장실휴지도둑', 'resources/uploadFiles/member/2024032609000082222.png', '이런 거 하나 있으면 ㅠ');
INSERT INTO TB_TOWN_REPLY (TOWN_REPLY_NO, TOWN_REPLY_REF_NO, TOWN_REPLY_WRITER, TOWN_REPLY_WRITER_IMG, TOWN_REPLY_CONTENT)
VALUES (SEQ_TOWN_REPLY_NO.NEXTVAL, 1, '기사식당명함도둑', 'resources/uploadFiles/member/2024032609000082223.jpg', '로또 당첨되면 여기부터 산다...');
INSERT INTO TB_TOWN_REPLY (TOWN_REPLY_NO, TOWN_REPLY_REF_NO, TOWN_REPLY_WRITER, TOWN_REPLY_WRITER_IMG, TOWN_REPLY_CONTENT)
VALUES (SEQ_TOWN_REPLY_NO.NEXTVAL, 3, '휴게소컵도둑', 'resources/uploadFiles/member/2024032609000082224.jpg', '사진 너무 이뻐요 ㅎㅎ');
INSERT INTO TB_TOWN_REPLY (TOWN_REPLY_NO, TOWN_REPLY_REF_NO, TOWN_REPLY_WRITER, TOWN_REPLY_WRITER_IMG, TOWN_REPLY_CONTENT)
VALUES (SEQ_TOWN_REPLY_NO.NEXTVAL, 3, '주호민이알려주는고데기사용법', 'resources/uploadFiles/member/2024032609000082225.jpg', '정말 좋네요!');
INSERT INTO TB_TOWN_REPLY (TOWN_REPLY_NO, TOWN_REPLY_REF_NO, TOWN_REPLY_WRITER, TOWN_REPLY_WRITER_IMG, TOWN_REPLY_CONTENT)
VALUES (SEQ_TOWN_REPLY_NO.NEXTVAL, 4, '주호민이알려주는고데기사용법', 'resources/uploadFiles/member/2024032609000082225.jpg', '같이 걸으실 분 구함');
--------------------------------------------------
----------------- TOWN-STAR 관련 -----------------	
--------------------------------------------------
CREATE TABLE TB_TOWN_STAR (
    TOWN_STAR_REF_NO NUMBER CONSTRAINT TOWN_STAR_REF_NO_NN NOT NULL,
    TOWN_STAR_USER_NO NUMBER CONSTRAINT TOWN_STAR_USER_NO_NN NOT NULL
);

COMMENT ON COLUMN TB_TOWN_STAR.TOWN_STAR_REF_NO IS '즐겨찾기 동네소식 번호';
COMMENT ON COLUMN TB_TOWN_STAR.TOWN_STAR_USER_NO IS '즐겨찾기 회원번호';

INSERT INTO TB_TOWN_STAR VALUES(1, 2);
INSERT INTO TB_TOWN_STAR VALUES(2, 3);
INSERT INTO TB_TOWN_STAR VALUES(4, 3);
INSERT INTO TB_TOWN_STAR VALUES(4, 4);
INSERT INTO TB_TOWN_STAR VALUES(5, 5);
INSERT INTO TB_TOWN_STAR VALUES(5, 2);
--------------------------------------------------
----------------- NOTICE 알림 관련 -----------------	
--------------------------------------------------
CREATE TABLE TB_NOTICE (
    NOTICE_NO NUMBER CONSTRAINT NOTICE_NO_PK PRIMARY KEY,
    NOTICE_TITLE VARCHAR2(100) CONSTRAINT NOTICE_TITLE_NN NOT NULL,
    NOTICE_CONTENT VARCHAR2(4000) CONSTRAINT NOTICE_CONTENT_NN NOT NULL,
    NOTICE_WRITER NUMBER CONSTRAINT NOTICE_WRITER_NN NOT NULL,
    NOTICE_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT NOTICE_CREATE_DATE_NN NOT NULL,
    NOTICE_TYPE NUMBER DEFAULT 1 CONSTRAINT NOTICE_TYPE_CK CHECK (NOTICE_TYPE IN(1, 2, 3, 4)),
    NOTICE_STATUS VARCHAR2(1) DEFAULT 'N' CONSTRAINT NOTICE_STATUS_CK CHECK (NOTICE_STATUS IN('Y', 'N')),
    NOTICE_RECEIVER_NO NUMBER,
    NOTICE_ANNOUNCEMENT_NO NUMBER,
    NOTICE_QNA_NO NUMBER,
    NOTICE_APT_NO NUMBER,
    CONSTRAINT NOTICE_WRITER_FK FOREIGN KEY(NOTICE_WRITER) REFERENCES TB_MEMBER(USER_NO),
    CONSTRAINT NOTICE_ANNOUNCEMENT_NO_FK FOREIGN KEY(NOTICE_ANNOUNCEMENT_NO) REFERENCES TB_ANNOUNCEMENT(ANNOUNCEMENT_NO),
    CONSTRAINT NOTICE_QNA_NO_FK FOREIGN KEY(NOTICE_QNA_NO) REFERENCES TB_QNA(QNA_NO),
    CONSTRAINT NOTICE_APT_NO_FK FOREIGN KEY(NOTICE_APT_NO) REFERENCES TB_APT(APT_NO)
);

COMMENT ON COLUMN TB_NOTICE.NOTICE_NO IS '알림 번호';
COMMENT ON COLUMN TB_NOTICE.NOTICE_TITLE IS '알림 제목';
COMMENT ON COLUMN TB_NOTICE.NOTICE_CONTENT IS '알림 내용';
COMMENT ON COLUMN TB_NOTICE.NOTICE_WRITER IS '알림 작성자회원번호';
COMMENT ON COLUMN TB_NOTICE.NOTICE_CREATE_DATE IS '알림 작성일';
COMMENT ON COLUMN TB_NOTICE.NOTICE_TYPE IS '알림 유형 (1 : 일반 공지 / 2 : 프로젝트 알림 / 3 : QNA 알림)';
COMMENT ON COLUMN TB_NOTICE.NOTICE_STATUS IS '알림 상태값 (Y : 읽음 / N : 안읽음)';
COMMENT ON COLUMN TB_NOTICE.NOTICE_RECEIVER_NO IS '알림 수신자';
COMMENT ON COLUMN TB_NOTICE.NOTICE_ANNOUNCEMENT_NO IS '알림 참조글 (공지)';
COMMENT ON COLUMN TB_NOTICE.NOTICE_QNA_NO IS '알림 참조글 (QNA)';
COMMENT ON COLUMN TB_NOTICE.NOTICE_APT_NO IS '알림 참조글 (부동산)';

CREATE SEQUENCE SEQ_NOTICE_NO
NOCACHE;

INSERT INTO TB_NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_WRITER, NOTICE_CREATE_DATE, NOTICE_TYPE, NOTICE_ANNOUNCEMENT_NO)
VALUES (SEQ_NOTICE_NO.NEXTVAL, '공지사항', '안녕하세요. 갓물주 입니다. 갓물주는 부동산 정보 조회 사이트로 이제 여러분을 찾아뵙습니다.', 1, '2024-03-26', 1, 1);
--------------------------------------------------
------------------ DIBS 관련 ---------------------	
--------------------------------------------------
CREATE TABLE TB_DIBS (
    DIBS_USER_NO NUMBER, 
    DIBS_APT_NO NUMBER, 
    DIBS_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT DIBS_CREATE_DATE_NN NOT NULL,
    DIBS_STATUS VARCHAR2(1) DEFAULT 'N' CONSTRAINT DIBS_STATUS_CK CHECK(DIBS_STATUS IN('Y', 'N')),
    CONSTRAINT DIBS_PK PRIMARY KEY (DIBS_USER_NO, DIBS_APT_NO),
    CONSTRAINT DIBS_USER_NO_FK FOREIGN KEY (DIBS_USER_NO) REFERENCES TB_MEMBER(USER_NO),
    CONSTRAINT DIBS_APT_NO_FK FOREIGN KEY (DIBS_APT_NO) REFERENCES TB_APT(APT_NO)
);

COMMENT ON COLUMN TB_DIBS.DIBS_USER_NO IS '찜 회원번호';
COMMENT ON COLUMN TB_DIBS.DIBS_APT_NO IS '찜 프로젝트번호';
COMMENT ON COLUMN TB_DIBS.DIBS_CREATE_DATE IS '찜 등록일';
COMMENT ON COLUMN TB_DIBS.DIBS_STATUS IS '찜 상태값 (Y : 찜 / N : 찜 해제)';

CREATE SEQUENCE SEQ_DIBS_NO
NOCACHE;
--------------------------------------------------
----------------- ATTACHMENT 관련 -----------------	
--------------------------------------------------
CREATE TABLE TB_ATTACHMENT (
    ATTACHMENT_NO NUMBER CONSTRAINT ATTACHMENT_NO_PK PRIMARY KEY,
    ATTACHMENT_ORIGIN_NAME VARCHAR2(255) CONSTRAINT ATTACHMENT_ORIGIN_NAME_NN NOT NULL,
    ATTACHMENT_UPDATE_NAME VARCHAR2(255) CONSTRAINT ATTACHMENT_UPDATE_NAME_NN NOT NULL,
    ATTACHMENT_PATH VARCHAR2(1000),
    ATTACHMENT_UPLOAD_DATE DATE DEFAULT SYSDATE CONSTRAINT ATTACHMENT_UPLOAD_DATE_NN NOT NULL,
    ATTACHMENT_LEVEL NUMBER CONSTRAINT ATTACHMENT_LEVEL_NN NOT NULL,
    ATTACHMENT_STATUS VARCHAR2(1) DEFAULT 'Y' CONSTRAINT ATTACHMENT_STATUS_CK CHECK(ATTACHMENT_STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN TB_ATTACHMENT.ATTACHMENT_NO IS '파일 번호';
COMMENT ON COLUMN TB_ATTACHMENT.ATTACHMENT_ORIGIN_NAME IS '파일 원본파일명';
COMMENT ON COLUMN TB_ATTACHMENT.ATTACHMENT_UPDATE_NAME IS '파일 수정파일명';
COMMENT ON COLUMN TB_ATTACHMENT.ATTACHMENT_PATH IS '파일 저장폴더경로';
COMMENT ON COLUMN TB_ATTACHMENT.ATTACHMENT_UPLOAD_DATE IS '파일 업로드일';
COMMENT ON COLUMN TB_ATTACHMENT.ATTACHMENT_LEVEL IS '파일 레벨 (1 : 메인 / 2 : 서브)';
COMMENT ON COLUMN TB_ATTACHMENT.ATTACHMENT_STATUS IS '파일 상태값 (Y : 유효 / N : 비유효)';

CREATE SEQUENCE SEQ_ATTACHMENT_NO
NOCACHE;
--------------------------------------------------
------------------ SHARE 관련 ---------------------	
--------------------------------------------------
CREATE TABLE TB_SHARE (
    SHARE_APT_NO NUMBER CONSTRAINT SHARE_APT_NO_NN NOT NULL,
    SHARE_COUNT NUMBER DEFAULT 0,
    CONSTRAINT SHARE_APT_NO_FK FOREIGN KEY (SHARE_APT_NO) REFERENCES TB_APT(APT_NO)
);

COMMENT ON COLUMN TB_SHARE.SHARE_APT_NO IS '공유 부동산 번호';
COMMENT ON COLUMN TB_SHARE.SHARE_COUNT IS '공유 횟수';
--------------------------------------------------
------------------- LIKES 관련 ---------------------	
--------------------------------------------------
CREATE TABLE TB_LIKES (
    LIKES_APT_NO NUMBER CONSTRAINT LIKES_APT_NO_NN NOT NULL,
    LIKES_COUNT NUMBER DEFAULT 0,
    CONSTRAINT LIKES_APT_NO_FK FOREIGN KEY (LIKES_APT_NO) REFERENCES TB_APT(APT_NO)
);

COMMENT ON COLUMN TB_LIKES.LIKES_APT_NO IS '좋아요 부동산 번호';
COMMENT ON COLUMN TB_LIKES.LIKES_COUNT IS '좋아요 횟수';

--------------------------------------------------
---------------- IMPROVEMENT 관련 ------------------	
--------------------------------------------------
CREATE TABLE TB_IMPROVEMENT (
    IMP_REPLY_NO NUMBER CONSTRAINT IMP_REPLY_NO_PK PRIMARY KEY,
    IMP_REPLY_CONTENT VARCHAR2(600) CONSTRAINT IMP_REPLY_CONTENT_NN NOT NULL,
    IMP_REPLY_WRITER VARCHAR2(50) CONSTRAINT IMP_REPLY_WRITER_NN NOT NULL,
    IMP_REPLY_PROFILE VARCHAR2(100) CONSTRAINT IMP_REPLY_PROFILE_NN NOT NULL,
    IMP_REPLY_TYPE VARCHAR2(1) DEFAULT 'O' CONSTRAINT IMP_REPLY_TYPE_CK CHECK(IMP_REPLY_TYPE IN('O', 'S')),
    IMP_REPLY_CREATE_DATE DATE DEFAULT SYSDATE,
    IMP_REPLY_MODIFY_DATE DATE DEFAULT SYSDATE,
    IMP_REPLY_STATUS VARCHAR2(1) DEFAULT 'Y' CONSTRAINT IMP_REPLY_STATUS_CK CHECK(IMP_REPLY_STATUS IN('Y', 'N'))
);

CREATE SEQUENCE SEQ_IMP_REPLY_NO
NOCACHE;

COMMENT ON COLUMN TB_IMPROVEMENT.IMP_REPLY_NO IS '개선의견 번호';
COMMENT ON COLUMN TB_IMPROVEMENT.IMP_REPLY_CONTENT IS '개선의견 내용';
COMMENT ON COLUMN TB_IMPROVEMENT.IMP_REPLY_WRITER IS '개선의견 작성자 닉네임';
COMMENT ON COLUMN TB_IMPROVEMENT.IMP_REPLY_PROFILE IS '개선의견 작성자 이미지';
COMMENT ON COLUMN TB_IMPROVEMENT.IMP_REPLY_TYPE IS '개선의견 상태값 (O : 일반 / S : 비밀)';
COMMENT ON COLUMN TB_IMPROVEMENT.IMP_REPLY_CREATE_DATE IS '개선의견 작성일';
COMMENT ON COLUMN TB_IMPROVEMENT.IMP_REPLY_MODIFY_DATE IS '개선의견 수정일';
COMMENT ON COLUMN TB_IMPROVEMENT.IMP_REPLY_STATUS IS '개선의견 상태값 (Y : 게시 / N : 비게시)';

INSERT INTO TB_IMPROVEMENT (IMP_REPLY_NO, IMP_REPLY_CONTENT, IMP_REPLY_WRITER, IMP_REPLY_PROFILE, IMP_REPLY_TYPE) VALUES (SEQ_IMP_REPLY_NO.NEXTVAL, '사이트가 너무 이뻐요', '돼지불백집이쑤시개도둑', 'resources/uploadFiles/member/2024032609000082221.png', 'O');
INSERT INTO TB_IMPROVEMENT (IMP_REPLY_NO, IMP_REPLY_CONTENT, IMP_REPLY_WRITER, IMP_REPLY_PROFILE, IMP_REPLY_TYPE) VALUES (SEQ_IMP_REPLY_NO.NEXTVAL, '주호민이알려주는고데기사용법 저 회원 너무 시끄러워요', '돼지불백집이쑤시개도둑', 'resources/uploadFiles/member/2024032609000082221.png', 'O');
INSERT INTO TB_IMPROVEMENT (IMP_REPLY_NO, IMP_REPLY_CONTENT, IMP_REPLY_WRITER, IMP_REPLY_PROFILE, IMP_REPLY_TYPE) VALUES (SEQ_IMP_REPLY_NO.NEXTVAL, '앞으로도 화이팅!', '공중화장실휴지도둑', 'resources/uploadFiles/member/2024032609000082222.png', 'O');
INSERT INTO TB_IMPROVEMENT (IMP_REPLY_NO, IMP_REPLY_CONTENT, IMP_REPLY_WRITER, IMP_REPLY_PROFILE, IMP_REPLY_TYPE) VALUES (SEQ_IMP_REPLY_NO.NEXTVAL, '주호민 저 사람 제재해주실 수 있을까요?', '공중화장실휴지도둑', 'resources/uploadFiles/member/2024032609000082222.png', 'O');
INSERT INTO TB_IMPROVEMENT (IMP_REPLY_NO, IMP_REPLY_CONTENT, IMP_REPLY_WRITER, IMP_REPLY_PROFILE, IMP_REPLY_TYPE) VALUES (SEQ_IMP_REPLY_NO.NEXTVAL, '지도가 참 아름답네요', '기사식당명함도둑', 'resources/uploadFiles/member/2024032609000082223.jpg', 'O');
INSERT INTO TB_IMPROVEMENT (IMP_REPLY_NO, IMP_REPLY_CONTENT, IMP_REPLY_WRITER, IMP_REPLY_PROFILE, IMP_REPLY_TYPE) VALUES (SEQ_IMP_REPLY_NO.NEXTVAL, '신고 기능도 추가해주세요! 신고하고 싶은 사람이 있어요! ㅎㅎ', '휴게소컵도둑', 'resources/uploadFiles/member/2024032609000082224.jpg', 'O');
INSERT INTO TB_IMPROVEMENT (IMP_REPLY_NO, IMP_REPLY_CONTENT, IMP_REPLY_WRITER, IMP_REPLY_PROFILE, IMP_REPLY_TYPE) VALUES (SEQ_IMP_REPLY_NO.NEXTVAL, '억울해요', '주호민이알려주는고데기사용법', 'resources/uploadFiles/member/2024032609000082225.jpg', 'O');

--------------------------------------------------
---------------- IMP_CHOOSE 관련 ------------------	
--------------------------------------------------
CREATE TABLE TB_IMP_CHOOSE (
    IMP_CHOOSE_USER_NO NUMBER,
    IMP_CHOOSE_REPLY_NO NUMBER,
    IMP_CHOOSE_CREATE_DATE DATE DEFAULT SYSDATE,
    IMP_CHOOSE_STATUS VARCHAR2(1) CONSTRAINT IMP_CHOOSE_STATUS_CK CHECK(IMP_CHOOSE_STATUS IN ('1', '2')),
    CONSTRAINT IMP_CHOOSE_USER_NO_FK FOREIGN KEY (IMP_CHOOSE_USER_NO) REFERENCES TB_MEMBER(USER_NO),
    CONSTRAINT IMP_CHOOSE_REPLY_NO_FK FOREIGN KEY (IMP_CHOOSE_REPLY_NO) REFERENCES TB_IMPROVEMENT(IMP_REPLY_NO)
);

CREATE OR REPLACE TRIGGER remove_duplicate_imp_choose
BEFORE INSERT ON TB_IMP_CHOOSE
FOR EACH ROW
DECLARE
    existing_row_count NUMBER;
BEGIN
    -- 중복된 행의 수를 카운트
    SELECT COUNT(*)
    INTO existing_row_count
    FROM TB_IMP_CHOOSE
    WHERE IMP_CHOOSE_USER_NO = :NEW.IMP_CHOOSE_USER_NO
    AND IMP_CHOOSE_REPLY_NO = :NEW.IMP_CHOOSE_REPLY_NO;

    -- 중복된 행이 있으면 삭제
    IF existing_row_count > 0 THEN
        DELETE FROM TB_IMP_CHOOSE
        WHERE IMP_CHOOSE_USER_NO = :NEW.IMP_CHOOSE_USER_NO
        AND IMP_CHOOSE_REPLY_NO = :NEW.IMP_CHOOSE_REPLY_NO;
    END IF;
END;
/

COMMENT ON COLUMN TB_IMP_CHOOSE.IMP_CHOOSE_USER_NO IS '의견 좋아요싫어요 회원번호';
COMMENT ON COLUMN TB_IMP_CHOOSE.IMP_CHOOSE_REPLY_NO IS '의견 좋아요싫어요 의견번호';
COMMENT ON COLUMN TB_IMP_CHOOSE.IMP_CHOOSE_CREATE_DATE IS '의견 좋아요싫어요 등록일';
COMMENT ON COLUMN TB_IMP_CHOOSE.IMP_CHOOSE_STATUS IS '의견 좋아요싫어요 상태 (1 : 좋아요 / 2 : 싫어요)';

INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(2, 1, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(3, 1, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(4, 1, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(5, 1, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(2, 2, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(3, 2, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(4, 2, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(5, 2, 2);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(1, 3, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(3, 3, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(4, 3, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(5, 3, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(1, 4, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(3, 4, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(4, 4, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(5, 4, 2);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(1, 5, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(2, 5, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(4, 5, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(5, 5, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(1, 6, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(2, 6, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(3, 6, 1);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(5, 6, 2);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(1, 7, 2);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(2, 7, 2);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(3, 7, 2);
INSERT INTO TB_IMP_CHOOSE(IMP_CHOOSE_USER_NO, IMP_CHOOSE_REPLY_NO, IMP_CHOOSE_STATUS) VALUES(4, 7, 2);











COMMIT;






